Repository atlassian-labs/cyclops, pull requests merged in 2020-09, with the labels that each got.

#4 Add Slack integration
  Makefile
  README.md
  cmd/manager/main.go
  deploy/crds/atlassian.com_cyclenoderequests_crd.yaml
  docs/README.md
  docs/deployment/README.md
  docs/deployment/cloud-providers/aws/README.md
  docs/deployment/cloud-providers/aws/iam_policy.json
  docs/deployment/messaging-providers/README.md
  go.mod
  go.sum
  pkg/apis/atlassian/v1/cyclenoderequest_types.go
  pkg/apis/atlassian/v1/cyclenodestatus_types.go
  pkg/apis/atlassian/v1/zz_generated.deepcopy.go
  pkg/controller/cyclenoderequest/controller.go
  pkg/controller/cyclenoderequest/transitioner/node.go
  pkg/controller/cyclenoderequest/transitioner/transitions.go
  pkg/controller/cyclenoderequest/transitioner/util.go
  pkg/controller/cyclenodestatus/controller.go
  pkg/controller/resource_manager.go
  pkg/notifications/interface.go
  pkg/notifications/notifierbuilder/notifierbuilder.go
  pkg/notifications/slack/builder.go
  pkg/notifications/slack/slack.go
Labels: enhancement

#5 Create docker-publish.yml for CD to Github Images
  .github/workflows/docker-publish.yml
Labels: enhancement

#6 Update docker-publish.yml to use PAT in repo
  .github/workflows/docker-publish.yml
Labels: bug

#8 Moved slack doc file
  docs/deployment/messaging-providers/slack/README.md
Labels: documentation

#17 Use commit ID for master rather than latest
  .github/workflows/docker-publish.yml
Labels: enhancement
